#-------------------------------
# General Site Settings
baseURL = "http://example.org/"
languageCode = "en-us"
title = "hello its caleb"
googleAnalytics = "" # Add your identifier. For example UA-99631805-1.
paginate = 3


[params]
  description = "Personal Portfolio Theme for HUGO"
  color_scheme = "light" # You have the option to choose between three modes: auto, light, and dark. The default mode is set to auto, which means that the color scheme will automatically adapt based on your operating system settings. This way, you can enjoy a personalized experience without having to manually switch between light and dark modes.


#-------------------------------
# Global Cover
[params.global.cover]
  enable = false
  homepage_image = 'https://via.placeholder.com/1920x1080' # This line allows you to add a beautiful image at the top of your site, creating an eye-catching visual element that enhances the overall appearance and appeal.


#-------------------------------
# Breadcrumbs
[params.breadcrumbs]
  enable = false # This line of code enables you to easily incorporate breadcrumbs into your website. By setting the "enable" parameter to "true", breadcrumbs will be enabled on your website, allowing users to easily track their navigation and find relevant information. Conversely, setting the parameter to "false" will disable the display of breadcrumbs, removing this navigation feature from your website.


#-------------------------------
# Main Menu
[menu]
  [[menu.main]]
    name = "portfolio"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "about"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "say hey"
    url = "/contact/"
    weight = 3

  #-------------------------------
  # Author Settings
  [params.author]
    author_name = "caleb allen"
    author_role = "Lead Designer & Storyteller"
    author_bio = "A design-savvy storyteller turning ideas into products and campaigns."
    cta_button_text = ""
    cta_button_link = "/contact/"


  #-------------------------------
  # Projects Settings
  [params.projects]
    enable = true
    projects__title= "Portfolio"
    projects__description= ""


  #-------------------------------
  # Social Icons Settings

  [[params.social]]
    icon = "fa-brands fa-vimeo-v"
    name = "instagram"
    link = "https://www.linkedin.com/in/caleballen92"

  # Example of adding a new link to the footer:
  # [[params.social]]
  #   icon = "fa fa-linkedin"
  #   name = "Instagram"
  #   link = "https://instagram.com"

  # Other icons can be found at https://fontawesome.com/search?o=r&m=free


  #-------------------------------
  # Contact Settings
  [params.contact]
    contact__email = "your@email.com" # Add your form_id

    # NOTE
    # Priam theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


  #-------------------------------
  # Comment Section (Disqus)
  [params.disqus]
    enable = false
    disqusShortname = "anvod-studio-test" # Add your shortname for Disqus Comment. For example anvod-studio-test


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.tableOfContents]
    startLevel = 2
    ordered = false
    endLevel = 3

[markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false